"""
DevFlow AI — Database Adapter
==============================
Handles connection setup, SQL model schemas, and CRUD utilities.
Supports Neon/PostgreSQL when DATABASE_URL is provided, with an automatic
graceful fallback to a local SQLite database (devflow_local.db) otherwise.
"""

import datetime
import json
import logging
from typing import Any, List, Optional
import uuid

from sqlalchemy import (
    Column,
    DateTime,
    ForeignKey,
    Integer,
    JSON,
    String,
    Text,
    create_engine,
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker

from config.settings import settings

logger = logging.getLogger(__name__)

# ── Connection Setup ─────────────────────────────────────────────────────────

db_url = settings.DATABASE_URL
if not db_url:
    # Fallback to local SQLite database in the workspace
    db_url = "sqlite:///devflow_local.db"
    logger.info(f"[Database] No DATABASE_URL found. Falling back to local SQLite: {db_url}")
else:
    # Ensure postgresql:// is used instead of postgres:// (SQLAlchemy compatibility)
    if db_url.startswith("postgres://"):
        db_url = db_url.replace("postgres://", "postgresql://", 1)
    logger.info("[Database] Connecting to PostgreSQL database (Neon)...")

# SQLite needs extra parameters for multi-threading compatibility
connect_args = {}
if db_url.startswith("sqlite"):
    connect_args = {"check_same_thread": False}

engine = create_engine(db_url, connect_args=connect_args)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()


# ══════════════════════════════════════════════════════════════════════════════
#  DATABASE MODELS
# ══════════════════════════════════════════════════════════════════════════════

class UserSession(Base):
    """Represents a single end-to-end SDLC pipeline run session."""
    __tablename__ = "user_sessions"

    session_id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String(255), nullable=False, index=True)  # Links to Supabase User ID
    prompt = Column(Text, nullable=False)
    status = Column(String(50), default="IDLE")
    review_cycle = Column(Integer, default=0)
    band_room_id = Column(String(255), nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    # Relationships
    agent_states = relationship("AgentState", back_populates="session", cascade="all, delete-orphan")
    artifacts = relationship("Artifact", back_populates="session", cascade="all, delete-orphan")
    events = relationship("Event", back_populates="session", cascade="all, delete-orphan")


class AgentState(Base):
    """Tracks the collaboration status cards of each agent in a session."""
    __tablename__ = "agent_states"

    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(String(36), ForeignKey("user_sessions.session_id"), nullable=False, index=True)
    agent_name = Column(String(100), nullable=False)
    state = Column(String(50), default="IDLE")
    updated_at = Column(DateTime, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow)

    session = relationship("UserSession", back_populates="agent_states")


class Artifact(Base):
    """Stores code and spec files generated by the agents."""
    __tablename__ = "artifacts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(String(36), ForeignKey("user_sessions.session_id"), nullable=False, index=True)
    artifact_type = Column(String(100), nullable=False)  # architecture, frontend_code, backend_code, tests, documentation, release_verdict
    payload = Column(JSON, nullable=False)  # Stores the full output payload from the agent
    updated_at = Column(DateTime, default=datetime.datetime.utcnow)

    session = relationship("UserSession", back_populates="artifacts")


class Event(Base):
    """Stores the Band chat room event logs for console feeds."""
    __tablename__ = "events"

    event_id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    session_id = Column(String(36), ForeignKey("user_sessions.session_id"), nullable=False, index=True)
    event_type = Column(String(100), nullable=False)
    sender = Column(String(100), nullable=False)
    timestamp = Column(DateTime, default=datetime.datetime.utcnow)
    payload_data = Column(JSON, nullable=False)

    session = relationship("UserSession", back_populates="events")


# ══════════════════════════════════════════════════════════════════════════════
#  DATABASE CRUD HELPER UTILITIES
# ══════════════════════════════════════════════════════════════════════════════

def init_db() -> None:
    """Initialize database tables if they do not exist."""
    Base.metadata.create_all(bind=engine)
    
    # Safely alter table to add band_room_id if it's missing (fallback migration)
    db = SessionLocal()
    try:
        from sqlalchemy import text
        # Attempt to add band_room_id column; ignores failure if already exists
        db.execute(text("ALTER TABLE user_sessions ADD COLUMN band_room_id VARCHAR(255)"))
        db.commit()
        logger.info("[Database] Added band_room_id column to user_sessions table.")
    except Exception:
        db.rollback()
    finally:
        db.close()
        
    logger.info("[Database] Database initialized and tables verified.")


def create_session(user_id: str, prompt: str, band_room_id: Optional[str] = None) -> str:
    """Create a new session record and initialize all 7 agent states to IDLE."""
    db = SessionLocal()
    try:
        session_id = str(uuid.uuid4())
        user_sess = UserSession(
            session_id=session_id,
            user_id=user_id,
            prompt=prompt,
            status="RUNNING",
            band_room_id=band_room_id
        )
        db.add(user_sess)
        
        # Initialize 7 agents in state
        agents = [
            "ArchitectAgent", "FrontendDevAgent", "BackendDevAgent",
            "CodeReviewerAgent", "QATesterAgent", "TechWriterAgent",
            "ReleaseManagerAgent"
        ]
        for agent in agents:
            db.add(AgentState(session_id=session_id, agent_name=agent, state="IDLE"))
            
        db.commit()
        logger.info(f"[Database] Created session {session_id} for user {user_id}")
        return session_id
    except Exception as e:
        db.rollback()
        logger.error(f"[Database] Failed to create session: {e}")
        raise
    finally:
        db.close()


def update_session(session_id: str, status: str, review_cycle: int) -> None:
    """Update global session execution parameters."""
    db = SessionLocal()
    try:
        sess = db.query(UserSession).filter(UserSession.session_id == session_id).first()
        if sess:
            sess.status = status
            sess.review_cycle = review_cycle
            db.commit()
    except Exception as e:
        db.rollback()
        logger.error(f"[Database] Failed to update session {session_id}: {e}")
    finally:
        db.close()


def save_agent_state(session_id: str, agent_name: str, state: str) -> None:
    """Save the active state card for a specific agent."""
    db = SessionLocal()
    try:
        agent_state = db.query(AgentState).filter(
            AgentState.session_id == session_id,
            AgentState.agent_name == agent_name
        ).first()
        if agent_state:
            agent_state.state = state
            db.commit()
    except Exception as e:
        db.rollback()
        logger.error(f"[Database] Failed to save agent state for {agent_name}: {e}")
    finally:
        db.close()


def save_artifact(session_id: str, artifact_type: str, payload: dict) -> None:
    """Save a generated file/blueprint payload to the database."""
    db = SessionLocal()
    try:
        # Check if it already exists to overwrite
        art = db.query(Artifact).filter(
            Artifact.session_id == session_id,
            Artifact.artifact_type == artifact_type
        ).first()
        
        if art:
            art.payload = payload
            art.updated_at = datetime.datetime.utcnow()
        else:
            art = Artifact(
                session_id=session_id,
                artifact_type=artifact_type,
                payload=payload
            )
            db.add(art)
            
        db.commit()
        logger.info(f"[Database] Saved {artifact_type} artifact for session {session_id}")
    except Exception as e:
        db.rollback()
        logger.error(f"[Database] Failed to save artifact {artifact_type}: {e}")
    finally:
        db.close()


def save_event(session_id: str, event_data: dict) -> None:
    """Save a Band room log event to the database history."""
    db = SessionLocal()
    try:
        ts = event_data.get("timestamp")
        timestamp = datetime.datetime.fromisoformat(ts.replace("Z", "+00:00")) if ts else datetime.datetime.utcnow()
        
        event = Event(
            event_id=event_data.get("event_id", str(uuid.uuid4())),
            session_id=session_id,
            event_type=event_data.get("event_type"),
            sender=event_data.get("sender"),
            timestamp=timestamp,
            payload_data=event_data.get("payload_data", {})
        )
        db.add(event)
        db.commit()
    except Exception as e:
        db.rollback()
        logger.error(f"[Database] Failed to save event: {e}")
    finally:
        db.close()


def get_session_state(session_id: str) -> dict:
    """Load and reassemble the complete session state dictionary from the database.

    Replicates the schema of the old local pipeline_state.json.
    """
    db = SessionLocal()
    try:
        sess = db.query(UserSession).filter(UserSession.session_id == session_id).first()
        if not sess:
            return {}

        # Load agent states
        agents_dict = {state.agent_name: state.state for state in sess.agent_states}
        
        # Load artifacts
        artifacts_dict = {
            "architecture": {},
            "frontend_code": {},
            "backend_code": {},
            "review_result": {},
            "tests": {},
            "documentation": {},
            "release_verdict": {}
        }
        for art in sess.artifacts:
            if art.artifact_type in artifacts_dict:
                artifacts_dict[art.artifact_type] = art.payload

        # Load events
        events_list = []
        for evt in sorted(sess.events, key=lambda x: x.timestamp):
            events_list.append({
                "event_id": evt.event_id,
                "event_type": evt.event_type,
                "sender": evt.sender,
                "timestamp": evt.timestamp.isoformat() + "Z",
                "room_id": sess.band_room_id or settings.BAND_ROOM_ID,
                "payload_data": evt.payload_data
            })

        return {
            "session_id": sess.session_id,
            "status": sess.status,
            "review_cycle": sess.review_cycle,
            "band_room_id": sess.band_room_id,
            "agents": agents_dict,
            "artifacts": artifacts_dict,
            "events": events_list
        }
    except Exception as e:
        logger.error(f"[Database] Failed to get session state for {session_id}: {e}")
        return {}
    finally:
        db.close()


def get_user_sessions(user_id: str) -> List[dict]:
    """Retrieve all historic run sessions for a specific user.

    Provides the data feed for displaying user history.
    """
    db = SessionLocal()
    try:
        sessions = db.query(UserSession).filter(
            UserSession.user_id == user_id
        ).order_by(UserSession.created_at.desc()).all()
        
        return [
            {
                "session_id": s.session_id,
                "prompt": s.prompt,
                "status": s.status,
                "created_at": s.created_at.isoformat() + "Z"
            }
            for s in sessions
        ]
    except Exception as e:
        logger.error(f"[Database] Failed to query user sessions for {user_id}: {e}")
        return []
    finally:
        db.close()

# Auto-initialize database tables at startup
init_db()

